# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a89398d3e35f5cfac35691266229bb92c0b318c8cb7265ef522342bb70db8dc10c57bafae43430d49c6b8741438c2efcff81598e08c7ef56fabf48719644d7ed

test:
  secret_key_base: 0784e7451ad752d7a040033be2b6d1deb57a52a547c888d9ed346b58250b303d91a75b50be661a6aa235b6ee4671495e27b9ea0d59fd39e10af85893206493f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
